name: CI

on:
  pull_request:
    branches:
    - master


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: whoami
    - name: Run a multi-line script
      run: date
        echo Add other actions to build,
        echo test, and deploy your project.
